{
 "title": "Weather Monitoring - Almaty",
 "tags": [
  "weather, custom-exporter, prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "city",
    "label": "Сity",
    "query": {
     "query": "label_values(weather_humidity_percent,city)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Actual vs Feels Like Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "weather_temperature_celsius", "legendFormat": "__auto" },
    {
     "expr": "weather_feels_like_celsius{city=\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(weather_requests_total[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(weather_requests_total{city=\"$city\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Visibility",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "weather_visibility_m", "legendFormat": "__auto" },
    {
     "expr": "weather_visibility_m{city=\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cloud Cover",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_cloudiness_percent", "legendFormat": "__auto" },
    {
     "expr": "weather_cloudiness_percent{city=\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_wind_speed_mps", "legendFormat": "__auto" },
    {
     "expr": "weather_wind_speed_mps{city=\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Atmospheric Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    { "expr": "weather_pressure_hpa", "legendFormat": "__auto" },
    {
     "expr": "weather_pressure_hpa{city=\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_humidity_percent", "legendFormat": "__auto" },
    {
     "expr": "weather_humidity_percent{city=\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5-min Temperature Change",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(weather_temperature_celsius[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "delta(weather_temperature_celsius{city=\"$city\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    { "expr": "weather_temperature_celsius", "legendFormat": "__auto" },
    {
     "expr": "weather_temperature_celsius{city=\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Temperature °C",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_temperature_celsius", "legendFormat": "__auto" },
    {
     "expr": "weather_temperature_celsius{city=\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}